### Common
---
server:
  port: 8000
  error:
#    include-binding-errors: always
    include-message: always

spring:
  application:
    name: IBCS-Code-Challenge
#  profiles:
#    active: pgsql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
---

---

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ibcs-code-challenge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12211221}

---

